before_install:
  - curl -O http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - curl -O http://static.rust-lang.org/cargo-dist/cargo-nightly-linux.tar.gz
  - (cd rust-nightly-x86_64-unknown-linux-gnu/ && sudo ./install.sh)
  - (cd cargo-nightly/ && sudo ./install.sh)
script:
  - cargo test
  - cargo build
branches:
  only:
    - master
